[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[build]
  command = "npm install && NODE_OPTIONS=--max_old_space_size=4096 npm run build -- --configuration=production"
  publish = "dist/briefing-buddy-ui"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"
