[[redirects]]
  from = "/api/*"
  to = "https://govab.app.n8n.cloud/webhook/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[build]
  command = "npm install && NODE_OPTIONS=--max_old_space_size=4096 npm run build -- --configuration=production"
  publish = "dist/briefing-buddy-ui"
