apiVersion: apps/v1
kind: Deployment
metadata:
  name: briefing-buddy-ui
  labels:
    app: briefing-buddy-ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: briefing-buddy-ui
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: briefing-buddy-ui
    spec:
      containers:
      - name: briefing-buddy-ui
        image: ${CONTAINER_REGISTRY}/briefing-buddy-ui:${IMAGE_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: briefing-buddy-ui-config
              key: NODE_ENV
        - name: WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: briefing-buddy-ui-secrets
              key: WEBHOOK_URL
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: briefing-buddy-ui-secrets
              key: SENTRY_DSN
      imagePullSecrets:
      - name: registry-credentials
